version: '3.9'
services:
  postgresdb:
    # container_name: postgresdb
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./build/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./postgres-data:/var/lib/postgresql/data
    restart : unless-stopped
    networks:
      - darknet

  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 6969:6969
  #   depends_on:
  #     - postgresdb
  #   networks:
  #     - darknet

networks:
  darknet:
    driver: bridge

volumes:
   postgres-data: