version: '3.9'
services:
  postgresdb:
    # container_name: postgresdb
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./build/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./postgres-data:/var/lib/postgresql/data
    restart : unless-stopped
    networks:
      - darknet
    environment:
      - POSTGRES_USER=pkbdytztfofcwf
      - POSTGRES_PASSWORD=ee6b8ea0ca73b0c591c993a67127bdb4fb29af099ffc354d32ce68507e809118
      - POSTGRES_URI=ec2-54-228-218-84.eu-west-1.compute.amazonaws.com
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=db65nuits093uo

  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 6969:6969
  #   depends_on:
  #     - postgresdb
  #   networks:
  #     - darknet

networks:
  darknet:
    driver: bridge

volumes:
   postgres-data: