version: '3.9'
services:
  postgresdb:
    # container_name: postgresdb
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./build/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./postgres-data:/var/lib/postgresql/data
    restart : unless-stopped
    networks:
      - darknet
    environment:
      - POSTGRES_USER=oktarcpjvgaorf
      - POSTGRES_PASSWORD=93f71f9ee4342d1fb1190493c57493ad405416c153f8bc281d7db4b3306555ad
      - POSTGRES_URI=ec2-52-30-67-143.eu-west-1.compute.amazonaws.com
      - POSTGRES_PORT=5432
      - POSTGRES_DB=d9pr4qe2pmgqs
      - POSTGRES_DATABASE=d9pr4qe2pmgqs


  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 6969:6969
  #   depends_on:
  #     - postgresdb
  #   networks:
  #     - darknet

networks:
  darknet:
    driver: bridge

volumes:
   postgres-data: