version: '3.8'
  
services:
  postgresdb:
    container_name: pastgresdb
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=testdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    # restart : unless-stopped

  # server:
  #   image: bazar-app
  #   container_name: bazar-app
  #   build: ./
  #   # command: ./app
  #   ports:
  #     - 6969:6969
  #   depends_on:
  #     - postgresdb
  #   networks:
  #     - darknet
  #   volumes:
  #     - ./bazar-app:/opt/bazar-app
  #   restart : unless-stopped  

networks:
  darknet:
    driver: bridge

# volumes:
#   postgres-data:
#   bazar-app: